name:                SomnaScript
version:             0.1.0.0
github:              "zer0-star/SomnaScript"
license:             MIT
author:              zer0-star
maintainer:          zer0-star
copyright:           "2022 zer0-star"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zer0-star/SomnaScript#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- megaparsec

library:
  source-dirs: src

executables:
  SomnaScript-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SomnaScript

tests:
  SomnaScript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SomnaScript
